# Navigation Links
# Clean minimalist menu structure

main:
  - name: _me
    url: /me/
    weight: 1
  - name: _research
    url: /research/
    weight: 2
  - name: _publications
    url: https://scholar.google.com/citations?user=j6a2kQkAAAAJ&hl=en
    weight: 3
  - name: _cv
    url: /uploads/resume.pdf
    weight: 4
  - name: _contact
    url: mailto:bjv30@cam.ac.uk
    weight: 5
